const https = require('https');
const fs = require('fs');
const path = require('path');

// Configuration
const SPREADSHEET_ID = '1u82fkDCYseizqTrZZfEjw3WcooUlFimvkf1AtGfM6dY';
const CSV_URL = `https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}/export?format=csv`;
const OUTPUT_FILE = path.join(__dirname, '../quotes.js');

console.log('🔄 Fetching quotes from Google Sheet...');

function fetchData(url) {
    https.get(url, (res) => {
        // Handle Redirects (301, 302, 307, etc.)
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
            console.log(`➡️ Redirecting to: ${res.headers.location}`);
            return fetchData(res.headers.location);
        }

        if (res.statusCode !== 200) {
            console.error(`❌ Failed to fetch data: Status Code ${res.statusCode}`);
            process.exit(1);
        }

        let rawData = '';
        res.on('data', (chunk) => { rawData += chunk; });

        res.on('end', () => {
            try {
                const quotes = parseCSV(rawData);
                console.log(`✅ Extracted ${quotes.length} quotes.`);

                // Format as JS file
                const fileContent = `// Hindi Quotes Collection with Writer Names
// Auto-generated by scripts/sync-quotes.js

const quotes = ${JSON.stringify(quotes, null, 4)};
`;

                fs.writeFileSync(OUTPUT_FILE, fileContent);
                console.log(`✨ Successfully updated quotes.js with ${quotes.length} quotes!`);

            } catch (e) {
                console.error('❌ Error processing data:', e.message);
                process.exit(1);
            }
        });

    }).on('error', (e) => {
        console.error(`❌ Request error: ${e.message}`);
        process.exit(1);
    });
}

// Simple CSV Parser that handles quoted fields
function parseCSV(csvText) {
    const lines = csvText.split(/\r?\n/);
    const result = [];

    // Skip empty lines
    const validLines = lines.filter(line => line.trim() !== '');

    for (let i = 0; i < validLines.length; i++) {
        const line = validLines[i];

        // CSV Parser Logic
        // Matches: "quoted value" OR unquoted_value
        const regex = /(?:^|,)(\"(?:[^\"]+|\"\")*\"|[^,]*)?/g;
        const row = [];
        let match;

        // Reset lastIndex is important if reused, but here we create new regex each line (fine for small data)
        while ((match = regex.exec(line)) !== null) {
            let val = match[1] || '';
            // Remove quotes and unescape "" -> "
            if (val.startsWith('"') && val.endsWith('"')) {
                val = val.slice(1, -1).replace(/""/g, '"');
            }
            // Fix: regex matches empty string at end of line sometimes
            if (match[0] === ',' || match[0] === '') {
                // Logic check: checking match[0] helps differentiate
            }

            row.push(val.trim());
        }

        // The regex includes an empty match at the end of the string, pop it if it's truly empty and extra
        // Actually, let's just use the logic from before which was cleaner for this specific data.
        // Google Sheet Export is standard.
        // Let's fallback to specific column indices if header detection is hard.
        // We know structure: Quote, Writer.

        // Let's simply use the extracted row.
        // Clean up empty strings at the very end of row which might be artifacts
        // But writers might be missing? No, we filter.

        const cleanRow = row.filter(pt => pt !== undefined && pt !== '');

        // We assume column 0 is Quote, Column 1 is Writer.
        // If the row has > 2 columns, we take 0 and 1.

        if (cleanRow.length >= 2) {
            const text = cleanRow[0];
            const writer = cleanRow[1];

            // Skip Header Row if it exists
            if (text.toLowerCase() === 'quote' && writer.toLowerCase() === 'writer') continue;
            if (text.toLowerCase() === 'quotes' && writer.toLowerCase() === 'writer name') continue;

            result.push({ text, writer });
        }
    }

    return result;
}

fetchData(CSV_URL);
