const https = require('https');
const fs = require('fs');
const path = require('path');

// Configuration
const SPREADSHEET_ID = '1u82fkDCYseizqTrZZfEjw3WcooUlFimvkf1AtGfM6dY';
const CSV_URL = `https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}/export?format=csv`;
const OUTPUT_FILE = path.join(__dirname, '../quotes.js');

console.log('🔄 Fetching quotes from Google Sheet...');

function fetchData(url) {
    https.get(url, (res) => {
        // Handle Redirects (301, 302, 307, etc.)
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
            console.log(`➡️ Redirecting to: ${res.headers.location}`);
            return fetchData(res.headers.location);
        }

        if (res.statusCode !== 200) {
            console.error(`❌ Failed to fetch data: Status Code ${res.statusCode}`);
            process.exit(1);
        }

        let rawData = '';
        res.on('data', (chunk) => { rawData += chunk; });

        res.on('end', () => {
            try {
                const quotes = parseCSV(rawData);
                console.log(`✅ Extracted ${quotes.length} quotes.`);

                // Format as JS file
                const fileContent = `// Hindi Quotes Collection with Writer Names
// Auto-generated by scripts/sync-quotes.js

const quotes = ${JSON.stringify(quotes, null, 4)};
`;

                fs.writeFileSync(OUTPUT_FILE, fileContent);
                console.log(`✨ Successfully updated quotes.js with ${quotes.length} quotes!`);

            } catch (e) {
                console.error('❌ Error processing data:', e.message);
                process.exit(1);
            }
        });

    }).on('error', (e) => {
        console.error(`❌ Request error: ${e.message}`);
        process.exit(1);
    });
}

// Simple CSV Parser that handles quoted fields
function parseCSV(csvText) {
    const lines = csvText.split(/\r?\n/);
    const result = [];

    // Skip empty lines
    const validLines = lines.filter(line => line.trim() !== '');

    for (let i = 0; i < validLines.length; i++) {
        const line = validLines[i];

        // CSV Parser Logic
        const regex = /(?:^|,)(\"(?:[^\"]+|\"\")*\"|[^,]*)?/g;
        const row = [];
        let match;

        while ((match = regex.exec(line)) !== null) {
            let val = match[1] || '';
            // Remove quotes and unescape "" -> "
            if (val.startsWith('"') && val.endsWith('"')) {
                val = val.slice(1, -1).replace(/""/g, '"');
            }
            if (match[0] === ',' || match[0] === '') {
                // Logic check
            }

            row.push(val.trim());
        }

        const cleanRow = row.filter(pt => pt !== undefined && pt !== '');

        // Updated Logic for New Structure: [Index, Quote, Writer]
        // We expect at least 3 columns

        if (cleanRow.length >= 3) {
            const text = cleanRow[1];
            const writer = cleanRow[2];

            // Skip Header Row (English and Hindi)
            if (text.toLowerCase() === 'quote' && writer.toLowerCase() === 'writer') continue;
            if (text === 'उद्धरण' && writer === 'लेखक') continue;

            if (text && writer) {
                result.push({ text, writer });
            }
        }
        // Fallback or header check for very first row if structure varies
        else if (cleanRow.length === 2) {
            // Maybe header or old format?
            const text = cleanRow[0];
            const writer = cleanRow[1];

            // Check if header
            if (text === 'उद्धरण' && writer === 'लेखक') continue;
            if (text.toLowerCase() === 'quote' && writer.toLowerCase() === 'writer') continue;

            // Assume data if not index
            // But if current sheet has index, this case shouldn't hit for data rows.
            // We'll leave it but prioritize the 3-column check which is standard now.
        }
    }

    return result;
}

fetchData(CSV_URL);
